<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:connectorconfiguration="http://wwww.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/studio/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/studio/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/studio/process" xsi:schemaLocation="http://www.bonitasoft.org/ns/studio/process/decision http://www.bonitasoft.org/ns/studio/process#//decision">
  <process:MainProcess xmi:id="_D_yDsA0pEeyMWNmCM-O3tg" name="RegistroDeSociedadAnonimaGrupo11Diagrama" author="jc" bonitaVersion="7.12.1" bonitaModelVersion="7.12.0-004">
    <elements xmi:type="process:Pool" xmi:id="_D_yDsQ0pEeyMWNmCM-O3tg" name="Registro de Sociedad Anónima">
      <elements xmi:type="process:Lane" xmi:id="_xfdJcBHFEeyJurGPsxsX6w" name="Apoderado" actor="_5sRBsBeKEeysAPdnhpesKQ">
        <elements xmi:type="process:StartEvent" xmi:id="_bxtn0A0pEeyMWNmCM-O3tg" name="Inicio" outgoing="_D_yDyA0pEeyMWNmCM-O3tg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D_yDtA0pEeyMWNmCM-O3tg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D_yDtQ0pEeyMWNmCM-O3tg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D_yDtg0pEeyMWNmCM-O3tg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_F-bSkBHHEeyJurGPsxsX6w" name="Solicitud de registro de S.A." outgoing="_pUAVgBHGEeyJurGPsxsX6w" incoming="_D_yDyA0pEeyMWNmCM-O3tg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_iAN-0BHGEeyJurGPsxsX6w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_iANXwBHGEeyJurGPsxsX6w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_iAN-0RHGEeyJurGPsxsX6w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_iAN-0hHGEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_iAN-0xHGEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_iAN-1BHGEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_iAN-1hHGEeyJurGPsxsX6w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_iAN-1RHGEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_F-cguRHHEeyJurGPsxsX6w">
            <targetForm xmi:type="expression:Expression" xmi:id="_MU0aADHeEey03K0u2MSwCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_F-cguBHHEeyJurGPsxsX6w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_F-cguxHHEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_uxqmIBHIEeyJurGPsxsX6w" name="Modificación de estatuto" outgoing="_wbPzEBHIEeyJurGPsxsX6w" incoming="_jQkUgBTIEeyu34YKztTfzQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_kiVEURHIEeyJurGPsxsX6w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_kiVEUBHIEeyJurGPsxsX6w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_kiVEUhHIEeyJurGPsxsX6w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_kiVEUxHIEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_kiVEVBHIEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_kiVEVRHIEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_kiVEVxHIEeyJurGPsxsX6w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_kiVEVhHIEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_uxqmKhHIEeyJurGPsxsX6w">
            <targetForm xmi:type="expression:Expression" xmi:id="_MU0aATHeEey03K0u2MSwCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_uxqmKRHIEeyJurGPsxsX6w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_uxqmLBHIEeyJurGPsxsX6w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_IL_hsBZ6EeyizpHOufPl4w" name="Subsanación de la solicitud de registro de S.A." outgoing="_S6pcwBZ6EeyizpHOufPl4w" incoming="_DB8tYBTHEeyu34YKztTfzQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_HOjCARZ6EeyizpHOufPl4w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_HOjCABZ6EeyizpHOufPl4w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_HOjCAhZ6EeyizpHOufPl4w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_HOjCAxZ6EeyizpHOufPl4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_HOjCBBZ6EeyizpHOufPl4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_HOjCBRZ6EeyizpHOufPl4w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_HOjCBxZ6EeyizpHOufPl4w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_HOjCBhZ6EeyizpHOufPl4w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_hRBFYBZ6EeyizpHOufPl4w" name="Plazo de subsanación indicado en el email" outgoing="_FsF_cBc4EeydQ9O-p9lJOQ">
            <condition xmi:type="expression:Expression" xmi:id="_-peikBeKEeysAPdnhpesKQ" name="14 días: 00:00:00" content="1209600000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_IMAIyRZ6EeyizpHOufPl4w">
            <targetForm xmi:type="expression:Expression" xmi:id="_MU0aAjHeEey03K0u2MSwCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_IMAIyBZ6EeyizpHOufPl4w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_IMAIyxZ6EeyizpHOufPl4w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_C_vt8Bc4EeydQ9O-p9lJOQ" name="Fin por expiración de plazo de subsanación" incoming="_FsF_cBc4EeydQ9O-p9lJOQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_C_vt8hc4EeydQ9O-p9lJOQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_C_vt8Rc4EeydQ9O-p9lJOQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_C_vt8xc4EeydQ9O-p9lJOQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_D_yDsg0pEeyMWNmCM-O3tg" name="Mesa de entradas" actor="_uBsmUA0pEey53pgTA4dkHg">
        <elements xmi:type="process:XORGateway" xmi:id="_udCMkA0rEey53pgTA4dkHg" name="¿La solicitud es correcta?" outgoing="_Uwub4A0qEey53pgTA4dkHg _Za0zgA0qEey53pgTA4dkHg" incoming="_LSnisA0qEey53pgTA4dkHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_G69l8Q0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_G69l8A0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_G69l8g0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_CW8oMA0qEey53pgTA4dkHg" name="Revisión de la solicitud" outgoing="_LSnisA0qEey53pgTA4dkHg" incoming="_pUAVgBHGEeyJurGPsxsX6w _S6pcwBZ6EeyizpHOufPl4w" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_D_yDuA0pEeyMWNmCM-O3tg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_D_yDuQ0pEeyMWNmCM-O3tg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_D_yDug0pEeyMWNmCM-O3tg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_D_yDuw0pEeyMWNmCM-O3tg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_D_yDvA0pEeyMWNmCM-O3tg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_D_yDvQ0pEeyMWNmCM-O3tg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_D_yDvg0pEeyMWNmCM-O3tg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_D_yDvw0pEeyMWNmCM-O3tg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_CW8oOg0qEey53pgTA4dkHg">
            <targetForm xmi:type="expression:Expression" xmi:id="_MU0aAzHeEey03K0u2MSwCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_CW8oOQ0qEey53pgTA4dkHg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_CW8oPA0qEey53pgTA4dkHg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_v9kOABHHEeyJurGPsxsX6w" name="Generación de expediente" outgoing="_rr0qcCJ6EeyedeovCQb2XQ" incoming="_Uwub4A0qEey53pgTA4dkHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XkHzwQ0uEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XkHzwA0uEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XkHzwg0uEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_XkHzww0uEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_XkHzxA0uEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_XkHzxQ0uEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_XkHzxw0uEey53pgTA4dkHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_XkHzxg0uEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_7rVsMBTGEeyu34YKztTfzQ" name="Envío de correo informando plazo de subsanación al apoderado" outgoing="_DB8tYBTHEeyu34YKztTfzQ" incoming="_Za0zgA0qEey53pgTA4dkHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6YngEBTGEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6Ym5ABTGEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6YngERTGEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_hnLpgCF5Eey4IZyr5ymsjw" name="conector-email-plazo-subsanacion" definitionId="email" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_hnLpgSF5Eey4IZyr5ymsjw" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpgiF5Eey4IZyr5ymsjw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpgyF5Eey4IZyr5ymsjw" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLphCF5Eey4IZyr5ymsjw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_hnLphSF5Eey4IZyr5ymsjw" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLphiF5Eey4IZyr5ymsjw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_hnLphyF5Eey4IZyr5ymsjw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpiCF5Eey4IZyr5ymsjw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpiSF5Eey4IZyr5ymsjw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpiiF5Eey4IZyr5ymsjw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpiyF5Eey4IZyr5ymsjw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpjCF5Eey4IZyr5ymsjw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpjSF5Eey4IZyr5ymsjw" name="dssd.unlp.2021.grupo11@gmail.com" content="dssd.unlp.2021.grupo11@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpjiF5Eey4IZyr5ymsjw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpjyF5Eey4IZyr5ymsjw" name="grupo11helados" content="grupo11helados" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpkCF5Eey4IZyr5ymsjw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpkSF5Eey4IZyr5ymsjw" name="dssd.unlp.2021.grupo11@gmail.com" content="dssd.unlp.2021.grupo11@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpkiF5Eey4IZyr5ymsjw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpkyF5Eey4IZyr5ymsjw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLplCF5Eey4IZyr5ymsjw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_hnLplSF5Eey4IZyr5ymsjw" name="email_apoderado" content="email_apoderado" type="TYPE_VARIABLE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_hnLpliF5Eey4IZyr5ymsjw" name="email_apoderado" dataType="_D_yD4Q0pEeyMWNmCM-O3tg"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLplyF5Eey4IZyr5ymsjw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpmCF5Eey4IZyr5ymsjw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpmSF5Eey4IZyr5ymsjw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpmiF5Eey4IZyr5ymsjw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpmyF5Eey4IZyr5ymsjw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpnCF5Eey4IZyr5ymsjw" name="Subsanación - Solicitud de Registro de S.A." content="Subsanación - Solicitud de Registro de S.A." returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpnSF5Eey4IZyr5ymsjw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpniF5Eey4IZyr5ymsjw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpnyF5Eey4IZyr5ymsjw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpoCF5Eey4IZyr5ymsjw" name="&lt;pattern-expression>" content="Mesa de Entradas le informa que:&#xA;&#xA;Su solicitud de Registro de la S.A. ${nombre_sociedad} requiere modificación de los datos cargados por información incorrecta.&#xA;&#xA;Dispone de 14 días para realizar las modificaciones pertinentes.&#xA;&#xA;/* Acá puede ir una URL generada dinámicamente para que pueda entrar a editar los datos /*&#xA;&#xA;&#xA;Dirección Nacional de Personas Jurídicas&#xA;&#xA;Mesa de entradas.&#xA;" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_gjzroCJjEeyedeovCQb2XQ" name="nombre_sociedad" content="nombre_sociedad" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_gjzroSJjEeyedeovCQb2XQ" name="nombre_sociedad" content="nombre_sociedad" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_gjzroiJjEeyedeovCQb2XQ" name="nombre_sociedad" dataType="_D_yD4Q0pEeyMWNmCM-O3tg"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLppCF5Eey4IZyr5ymsjw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_hnLppSF5Eey4IZyr5ymsjw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLppiF5Eey4IZyr5ymsjw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_hnLppyF5Eey4IZyr5ymsjw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpqCF5Eey4IZyr5ymsjw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_hnLpqSF5Eey4IZyr5ymsjw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_hnLpqiF5Eey4IZyr5ymsjw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_hnLpqyF5Eey4IZyr5ymsjw"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6YngEhTGEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6YngExTGEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6YngFBTGEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6YngFhTGEeyu34YKztTfzQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6YngFRTGEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Ottw8BTHEeyu34YKztTfzQ" name="Envío de correo de confirmación al apoderado" outgoing="_cNnVgBTQEey7htL4S3IM2A" incoming="_rr0qcCJ6EeyedeovCQb2XQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Mv0g4RTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Mv0g4BTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Mv0g4hTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_l_GsACF5Eey4IZyr5ymsjw" name="conector-email-confirmación" definitionId="email" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_l_GsASF5Eey4IZyr5ymsjw" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsAiF5Eey4IZyr5ymsjw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsAyF5Eey4IZyr5ymsjw" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsBCF5Eey4IZyr5ymsjw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsBSF5Eey4IZyr5ymsjw" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsBiF5Eey4IZyr5ymsjw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsByF5Eey4IZyr5ymsjw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsCCF5Eey4IZyr5ymsjw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsCSF5Eey4IZyr5ymsjw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsCiF5Eey4IZyr5ymsjw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsCyF5Eey4IZyr5ymsjw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsDCF5Eey4IZyr5ymsjw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsDSF5Eey4IZyr5ymsjw" name="dssd.unlp.2021.grupo11@gmail.com" content="dssd.unlp.2021.grupo11@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsDiF5Eey4IZyr5ymsjw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsDyF5Eey4IZyr5ymsjw" name="grupo11helados" content="grupo11helados" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsECF5Eey4IZyr5ymsjw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsESF5Eey4IZyr5ymsjw" name="dssd.unlp.2021.grupo11@gmail.com" content="dssd.unlp.2021.grupo11@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsEiF5Eey4IZyr5ymsjw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsEyF5Eey4IZyr5ymsjw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsFCF5Eey4IZyr5ymsjw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsFSF5Eey4IZyr5ymsjw" name="email_apoderado" content="email_apoderado" type="TYPE_VARIABLE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_l_GsFiF5Eey4IZyr5ymsjw" name="email_apoderado" dataType="_D_yD4Q0pEeyMWNmCM-O3tg"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsFyF5Eey4IZyr5ymsjw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsGCF5Eey4IZyr5ymsjw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsGSF5Eey4IZyr5ymsjw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsGiF5Eey4IZyr5ymsjw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsGyF5Eey4IZyr5ymsjw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsHCF5Eey4IZyr5ymsjw" name="Confirmación - Solicitud de Registro de S.A." content="Confirmación - Solicitud de Registro de S.A." returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsHSF5Eey4IZyr5ymsjw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsHiF5Eey4IZyr5ymsjw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsHyF5Eey4IZyr5ymsjw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsICF5Eey4IZyr5ymsjw" name="&lt;pattern-expression>" content="Mesa de Entradas le informa que:&#xA;&#xA;Su solicitud de Registro de la S.A. ${nombre_sociedad} ha pasado exitosamente la etapa de evaluación por Mesa de Entradas.&#xA;&#xA;A la brevedad, será evaluada por el Área de Legales.&#xA;Le informaremos el resultado por este mismo medio.&#xA;&#xA;Dirección Nacional de Personas Jurídicas&#xA;&#xA;Mesa de entradas." type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_wM5gYCJjEeyedeovCQb2XQ" name="nombre_sociedad" content="nombre_sociedad" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_wM5gYSJjEeyedeovCQb2XQ" name="nombre_sociedad" content="nombre_sociedad" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_wM5gYiJjEeyedeovCQb2XQ" name="nombre_sociedad" dataType="_D_yD4Q0pEeyMWNmCM-O3tg"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsJCF5Eey4IZyr5ymsjw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_l_GsJSF5Eey4IZyr5ymsjw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsJiF5Eey4IZyr5ymsjw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsJyF5Eey4IZyr5ymsjw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsKCF5Eey4IZyr5ymsjw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_l_GsKSF5Eey4IZyr5ymsjw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_l_GsKiF5Eey4IZyr5ymsjw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_l_GsKyF5Eey4IZyr5ymsjw"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Mv0g4xTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Mv0g5BTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Mv0g5RTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Mv0g5xTHEeyu34YKztTfzQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Mv0g5hTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_Qjx2IA0xEeyr5fjvIKOl-A" name="Se obtuvo el código QR" outgoing="_q8fzIA0tEey53pgTA4dkHg _wqlXUA0tEey53pgTA4dkHg" incoming="_-iAMIC_1EeyieZ2hcAfZeA">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_o5uqIg0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_o5uqIQ0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_o5uqIw0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_eSovoA0tEey53pgTA4dkHg" name="Creación de carpeta física" outgoing="_f5gYEA0zEeyr5fjvIKOl-A" incoming="_q8fzIA0tEey53pgTA4dkHg" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_d4GIsQ0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_d4GIsA0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_d4GvwA0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_d4GvwQ0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_d4Gvwg0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_d4Gvww0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_d4GvxQ0tEey53pgTA4dkHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_d4GvxA0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_eSpWuQ0tEey53pgTA4dkHg">
            <targetForm xmi:type="expression:Expression" xmi:id="_MU0aBDHeEey03K0u2MSwCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_eSpWuA0tEey53pgTA4dkHg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_eSpWuw0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_i_7s8BTHEeyu34YKztTfzQ" name="Envío de correo de finalización al apoderado" outgoing="_-63OIBc1EeydQ9O-p9lJOQ" incoming="_f5gYEA0zEeyr5fjvIKOl-A">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_hxiAIRTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_hxiAIBTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_hxiAIhTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_yjwXEDHaEey03K0u2MSwCw" name="conector-email-finalizacion" definitionId="email" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_yjwXETHaEey03K0u2MSwCw" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXEjHaEey03K0u2MSwCw" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXEzHaEey03K0u2MSwCw" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXFDHaEey03K0u2MSwCw" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXFTHaEey03K0u2MSwCw" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXFjHaEey03K0u2MSwCw" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXFzHaEey03K0u2MSwCw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXGDHaEey03K0u2MSwCw" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXGTHaEey03K0u2MSwCw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXGjHaEey03K0u2MSwCw" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXGzHaEey03K0u2MSwCw" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXHDHaEey03K0u2MSwCw" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXHTHaEey03K0u2MSwCw" name="dssd.unlp.2021.grupo11@gmail.com" content="dssd.unlp.2021.grupo11@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXHjHaEey03K0u2MSwCw" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXHzHaEey03K0u2MSwCw" name="grupo11helados" content="grupo11helados" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXIDHaEey03K0u2MSwCw" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXITHaEey03K0u2MSwCw" name="dssd.unlp.2021.grupo11@gmail.com" content="dssd.unlp.2021.grupo11@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXIjHaEey03K0u2MSwCw" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXIzHaEey03K0u2MSwCw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXJDHaEey03K0u2MSwCw" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXJTHaEey03K0u2MSwCw" name="email_apoderado" content="email_apoderado" type="TYPE_VARIABLE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_5ApBUDHiEey03K0u2MSwCw" name="email_apoderado" dataType="_D_yD4Q0pEeyMWNmCM-O3tg"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXJzHaEey03K0u2MSwCw" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXKDHaEey03K0u2MSwCw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXKTHaEey03K0u2MSwCw" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXKjHaEey03K0u2MSwCw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXKzHaEey03K0u2MSwCw" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXLDHaEey03K0u2MSwCw" name="Trámite Finalizado - Solicitud de Registro de S.A." content="Trámite Finalizado - Solicitud de Registro de S.A." returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXLTHaEey03K0u2MSwCw" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXLjHaEey03K0u2MSwCw" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXLzHaEey03K0u2MSwCw" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXMDHaEey03K0u2MSwCw" name="&lt;pattern-expression>" content="&lt;!DOCTYPE html>&#xA;&lt;html>&#xA;&lt;head>&#xA;&lt;title>Registro de S.A. exitoso&lt;/title>&#xA;&lt;/head>&#xA;&lt;body>&#xA;&#xA;&lt;h1>¡La S.A. ${nombre_sociedad} se registró exitosamente!&lt;/h1>&#xA;&lt;p>Su trámite finalizó y la S.A. ya está registrada en nuestro sistema.&lt;/p>&#xA;&#xA;&lt;p>/* Acá puede ir una URL generada dinámicamente para que pueda entrar a ver la carpeta pública del Drive */&lt;/p>&#xA;&#xA;&lt;p>Dirección Nacional de Personas Jurídicas&lt;/p>&#xA;&lt;p>Mesa de entradas.&lt;/p>&#xA;&#xA;&lt;/body>&#xA;&lt;/html>" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_5ApoYDHiEey03K0u2MSwCw" name="nombre_sociedad" content="nombre_sociedad" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_5ApoYTHiEey03K0u2MSwCw" name="nombre_sociedad" content="nombre_sociedad" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_5ApoYjHiEey03K0u2MSwCw" name="nombre_sociedad" dataType="_D_yD4Q0pEeyMWNmCM-O3tg"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXNDHaEey03K0u2MSwCw" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_yjwXNTHaEey03K0u2MSwCw"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXNjHaEey03K0u2MSwCw" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXNzHaEey03K0u2MSwCw" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXODHaEey03K0u2MSwCw" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_yjwXOTHaEey03K0u2MSwCw" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_yjwXOjHaEey03K0u2MSwCw" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_yjwXOzHaEey03K0u2MSwCw"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_hxiAIxTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_hxiAJBTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_hxiAJRTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_hxiAJxTHEeyu34YKztTfzQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_hxiAJhTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_MpULUBHJEeyJurGPsxsX6w" name="Creación de carpeta digital" outgoing="_q7kEYA1AEeynMqaWPtKvZg" incoming="_wqlXUA0tEey53pgTA4dkHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_sQ9rsg0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_sQ9rsQ0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_sQ9rsw0tEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_sQ9rtA0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_sQ9rtQ0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_sQ9rtg0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_sQ9ruA0tEey53pgTA4dkHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_sQ9rtw0tEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ANDGateway" xmi:id="_lB3GEA1AEeynMqaWPtKvZg" name="Finalizó la creación de carpetas y se informó al apoderado" outgoing="_BFavQBc4EeydQ9O-p9lJOQ" incoming="_q7kEYA1AEeynMqaWPtKvZg _-63OIBc1EeydQ9O-p9lJOQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_lB6wcQ1AEeynMqaWPtKvZg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_lB6wcA1AEeynMqaWPtKvZg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_lB6wcg1AEeynMqaWPtKvZg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndTerminatedEvent" xmi:id="_ARMdABc4EeydQ9O-p9lJOQ" name="Fin" incoming="_BFavQBc4EeydQ9O-p9lJOQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ARMdAhc4EeydQ9O-p9lJOQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ARMdARc4EeydQ9O-p9lJOQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ARMdAxc4EeydQ9O-p9lJOQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_05eWcA0pEey53pgTA4dkHg" name="Legales" actor="_5OIpkA0pEey53pgTA4dkHg">
        <elements xmi:type="process:XORGateway" xmi:id="__jFkAA0qEey53pgTA4dkHg" name="¿El estatuto es válido?" outgoing="_KrhRAA0rEey53pgTA4dkHg _rGDNMA0sEey53pgTA4dkHg" incoming="_AsVEAA0rEey53pgTA4dkHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__jGLEQ0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__jGLEA0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__jGLEg0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_eA24kA0sEey53pgTA4dkHg" name="Evaluación de estatuto" outgoing="_AsVEAA0rEey53pgTA4dkHg" incoming="_wbPzEBHIEeyJurGPsxsX6w _cNnVgBTQEey7htL4S3IM2A" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_r-7n4Q0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_r-7n4A0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_r-7n4g0qEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_r-7n4w0qEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_r-7n5A0qEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_r-7n5Q0qEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_r-7n5w0qEey53pgTA4dkHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_r-7n5g0qEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:BoundaryTimerEvent" xmi:id="_fLZZEA0sEey53pgTA4dkHg" name="Plazo de verificación" outgoing="_qaSf0BOBEeyttrkuoBOBpQ">
            <condition xmi:type="expression:Expression" xmi:id="_hqxlkA0sEey53pgTA4dkHg" name="7 días: 00:00:00" content="604800000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_eA3fqQ0sEey53pgTA4dkHg">
            <targetForm xmi:type="expression:Expression" xmi:id="_MU0aBTHeEey03K0u2MSwCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_eA3fqA0sEey53pgTA4dkHg"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_eA3fqw0sEey53pgTA4dkHg" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_oVZDcA0sEey53pgTA4dkHg" name="Solicitar estampillado" outgoing="_-iAMIC_1EeyieZ2hcAfZeA" incoming="_rGDNMA0sEey53pgTA4dkHg _qaSf0BOBEeyttrkuoBOBpQ">
          <textAnnotationAttachment xmi:type="process:TextAnnotationAttachment" xmi:id="_GxxGUA0tEey53pgTA4dkHg" source="_xP4SMA0sEey53pgTA4dkHg"/>
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oVZqgQ0sEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oVZqgA0sEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oVZqgg0sEey53pgTA4dkHg" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oVZqgw0sEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oVZqhA0sEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oVZqhQ0sEey53pgTA4dkHg" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oVZqhw0sEey53pgTA4dkHg" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oVZqhg0sEey53pgTA4dkHg" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:TextAnnotation" xmi:id="_xP4SMA0sEey53pgTA4dkHg" text="Servicio web - Colegio de Escribanos&#xA;&#xA;1. Envía estatuto, número de expediente y credenciales del escribano &#xA;&#xA;2. Recibe número de hash e imagen png con código QR (Contiene una URL que permitirá acceder a la información pública de la sociedad (Nombre, fecha de creación y socios y el mismo QR) mediante el número de estampillado.)"/>
        <elements xmi:type="process:ServiceTask" xmi:id="_XnyI8BTHEeyu34YKztTfzQ" name="Envío de correo informando cambios sugeridos" outgoing="_jQkUgBTIEeyu34YKztTfzQ" incoming="_KrhRAA0rEey53pgTA4dkHg">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_UQ6TwhTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_UQ6TwRTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_UQ6TwxTHEeyu34YKztTfzQ" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_sZO58CcjEeypC5KNHT4RoA" name="conector-email-estatuto-rechazado" definitionId="email" event="ON_FINISH" ignoreErrors="true" definitionVersion="1.2.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_sZO58ScjEeypC5KNHT4RoA" definitionId="email" version="1.2.0" modelVersion="7.12.0-004">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO58icjEeypC5KNHT4RoA" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_sZO58ycjEeypC5KNHT4RoA" name="smtp.gmail.com" content="smtp.gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO59CcjEeypC5KNHT4RoA" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_sZO59ScjEeypC5KNHT4RoA" name="465" content="465" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO59icjEeypC5KNHT4RoA" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_sZO59ycjEeypC5KNHT4RoA" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO5-CcjEeypC5KNHT4RoA" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_sZO5-ScjEeypC5KNHT4RoA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO5-icjEeypC5KNHT4RoA" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_sZO5-ycjEeypC5KNHT4RoA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO5_CcjEeypC5KNHT4RoA" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_sZO5_ScjEeypC5KNHT4RoA" name="dssd.unlp.2021.grupo11@gmail.com" content="dssd.unlp.2021.grupo11@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO5_icjEeypC5KNHT4RoA" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_sZO5_ycjEeypC5KNHT4RoA" name="grupo11helados" content="grupo11helados" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6ACcjEeypC5KNHT4RoA" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6AScjEeypC5KNHT4RoA" name="dssd.unlp.2021.grupo11@gmail.com" content="dssd.unlp.2021.grupo11@gmail.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6AicjEeypC5KNHT4RoA" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6AycjEeypC5KNHT4RoA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6BCcjEeypC5KNHT4RoA" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6BScjEeypC5KNHT4RoA" name="email_apoderado" content="email_apoderado" type="TYPE_VARIABLE" returnTypeFixed="true">
                  <referencedElements xmi:type="process:Data" xmi:id="_sZO6BicjEeypC5KNHT4RoA" name="email_apoderado" dataType="_D_yD4Q0pEeyMWNmCM-O3tg"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6BycjEeypC5KNHT4RoA" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6CCcjEeypC5KNHT4RoA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6CScjEeypC5KNHT4RoA" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6CicjEeypC5KNHT4RoA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6CycjEeypC5KNHT4RoA" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6DCcjEeypC5KNHT4RoA" name="Estatuto Rechazado - Solicitud de Registro de S.A." content="Estatuto Rechazado - Solicitud de Registro de S.A." returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6DScjEeypC5KNHT4RoA" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6DicjEeypC5KNHT4RoA" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6DycjEeypC5KNHT4RoA" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6ECcjEeypC5KNHT4RoA" name="&lt;pattern-expression>" content="Legales le informa que:&#xA;&#xA;Su solicitud de Registro de la S.A. ${nombre_sociedad} requiere modificación del estatuto por información incorrecta.&#xA;&#xA;/* Acá puede ir una URL generada dinámicamente para que pueda entrar a editar los datos /*&#xA;&#xA;&#xA;Dirección Nacional de Personas Jurídicas&#xA;&#xA;Área de Legales.&#xA;" type="TYPE_PATTERN" returnTypeFixed="true">
                  <referencedElements xmi:type="expression:Expression" xmi:id="_4kt_YCcjEeypC5KNHT4RoA" name="nombre_sociedad" content="nombre_sociedad" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
                    <referencedElements xmi:type="expression:Expression" xmi:id="_4kt_YScjEeypC5KNHT4RoA" name="nombre_sociedad" content="nombre_sociedad" type="TYPE_VARIABLE">
                      <referencedElements xmi:type="process:Data" xmi:id="_4kt_YicjEeypC5KNHT4RoA" name="nombre_sociedad" dataType="_D_yD4Q0pEeyMWNmCM-O3tg"/>
                    </referencedElements>
                  </referencedElements>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6FCcjEeypC5KNHT4RoA" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_sZO6FScjEeypC5KNHT4RoA"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6FicjEeypC5KNHT4RoA" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6FycjEeypC5KNHT4RoA" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6GCcjEeypC5KNHT4RoA" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_sZO6GScjEeypC5KNHT4RoA" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_sZO6GicjEeypC5KNHT4RoA" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_sZO6GycjEeypC5KNHT4RoA"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_UQ6TxBTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_UQ6TxRTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_UQ6TxhTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_UQ6TyBTHEeyu34YKztTfzQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_UQ6TxxTHEeyu34YKztTfzQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:Data" xmi:id="_oTWIECGQEey4IZyr5ymsjw" name="nombre_sociedad" dataType="_D_yD4Q0pEeyMWNmCM-O3tg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_oTWIESGQEey4IZyr5ymsjw" content="" type="TYPE_READ_ONLY_SCRIPT"/>
      </data>
      <data xmi:type="process:Data" xmi:id="_wqEegB6HEeyoFsu5LGmH0g" name="estado_evaluacion" dataType="_D_yD4Q0pEeyMWNmCM-O3tg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_wqEegR6HEeyoFsu5LGmH0g" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_nXgRgB6IEeyoFsu5LGmH0g" name="email_apoderado" dataType="_D_yD4Q0pEeyMWNmCM-O3tg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_nXgRgR6IEeyoFsu5LGmH0g" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_VA7jkCGNEey4IZyr5ymsjw" name="numero_expediente" dataType="_D_yD4Q0pEeyMWNmCM-O3tg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_VA7jkSGNEey4IZyr5ymsjw" content=""/>
      </data>
      <data xmi:type="process:Data" xmi:id="_O6ZrECfsEey3NZ3qyBMFbg" name="numero_hash" dataType="_D_yD4Q0pEeyMWNmCM-O3tg">
        <defaultValue xmi:type="expression:Expression" xmi:id="_O6ZrESfsEey3NZ3qyBMFbg" content=""/>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_D_yDxA0pEeyMWNmCM-O3tg">
        <targetForm xmi:type="expression:Expression" xmi:id="_MU0aBjHeEey03K0u2MSwCw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_D_yDxg0pEeyMWNmCM-O3tg">
        <targetForm xmi:type="expression:Expression" xmi:id="_D_yDxw0pEeyMWNmCM-O3tg" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_D_yDyA0pEeyMWNmCM-O3tg" target="_F-bSkBHHEeyJurGPsxsX6w" source="_bxtn0A0pEeyMWNmCM-O3tg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_D_yDyQ0pEeyMWNmCM-O3tg"/>
        <condition xmi:type="expression:Expression" xmi:id="_D_yDyg0pEeyMWNmCM-O3tg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_LSnisA0qEey53pgTA4dkHg" target="_udCMkA0rEey53pgTA4dkHg" source="_CW8oMA0qEey53pgTA4dkHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_LSnisQ0qEey53pgTA4dkHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_uTCjEg0rEey53pgTA4dkHg" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Uwub4A0qEey53pgTA4dkHg" name="Es correcta" target="_v9kOABHHEeyJurGPsxsX6w" source="_udCMkA0rEey53pgTA4dkHg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Uwub4Q0qEey53pgTA4dkHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_uTCjEA0rEey53pgTA4dkHg" name="estado_evaluacion == &quot;Aprobado por empleado-mesa-de-entradas&quot;" content="estado_evaluacion == &quot;Aprobado por empleado-mesa-de-entradas&quot;" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Za0zgA0qEey53pgTA4dkHg" name="Es incorrecta" target="_7rVsMBTGEeyu34YKztTfzQ" source="_udCMkA0rEey53pgTA4dkHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Za1akA0qEey53pgTA4dkHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_uTCjEQ0rEey53pgTA4dkHg" name="estado_evaluacion==&quot;Rechazado por empleado-mesa-de-entradas&quot;" content="estado_evaluacion==&quot;Rechazado por empleado-mesa-de-entradas&quot;" interpreter="GROOVY" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_iSkcECJ6EeyedeovCQb2XQ" name="estado_evaluacion" dataType="_D_yD4Q0pEeyMWNmCM-O3tg">
            <defaultValue xmi:type="expression:Expression" xmi:id="_iSkcESJ6EeyedeovCQb2XQ" content=""/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_AsVEAA0rEey53pgTA4dkHg" target="__jFkAA0qEey53pgTA4dkHg" source="_eA24kA0sEey53pgTA4dkHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_AsVEAQ0rEey53pgTA4dkHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_AsVEAg0rEey53pgTA4dkHg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KrhRAA0rEey53pgTA4dkHg" name="El trámite es inválido" target="_XnyI8BTHEeyu34YKztTfzQ" source="__jFkAA0qEey53pgTA4dkHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KrhRAQ0rEey53pgTA4dkHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_KrhRAg0rEey53pgTA4dkHg" name="estado_evaluacion == &quot;Rechazado por escribano-area-legales&quot;" content="estado_evaluacion == &quot;Rechazado por escribano-area-legales&quot;" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_txGU4CJ6EeyedeovCQb2XQ" name="estado_evaluacion" dataType="_D_yD4Q0pEeyMWNmCM-O3tg">
            <defaultValue xmi:type="expression:Expression" xmi:id="_txGU4SJ6EeyedeovCQb2XQ" content=""/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rGDNMA0sEey53pgTA4dkHg" name="El trámite es válido" target="_oVZDcA0sEey53pgTA4dkHg" source="__jFkAA0qEey53pgTA4dkHg" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rGDNMQ0sEey53pgTA4dkHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_rGDNMg0sEey53pgTA4dkHg" name="estado_evaluacion == &quot;Aprobado por escribano-area-legales&quot;" content="estado_evaluacion == &quot;Aprobado por escribano-area-legales&quot;" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:Data" xmi:id="_vCqqcCJ6EeyedeovCQb2XQ" name="estado_evaluacion" dataType="_D_yD4Q0pEeyMWNmCM-O3tg">
            <defaultValue xmi:type="expression:Expression" xmi:id="_vCqqcSJ6EeyedeovCQb2XQ" content=""/>
          </referencedElements>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q8fzIA0tEey53pgTA4dkHg" target="_eSovoA0tEey53pgTA4dkHg" source="_Qjx2IA0xEeyr5fjvIKOl-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q8gaMA0tEey53pgTA4dkHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Qj05cA0xEeyr5fjvIKOl-A" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wqlXUA0tEey53pgTA4dkHg" target="_MpULUBHJEeyJurGPsxsX6w" source="_Qjx2IA0xEeyr5fjvIKOl-A">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wqlXUQ0tEey53pgTA4dkHg"/>
        <condition xmi:type="expression:Expression" xmi:id="_Qj05cQ0xEeyr5fjvIKOl-A" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_f5gYEA0zEeyr5fjvIKOl-A" target="_i_7s8BTHEeyu34YKztTfzQ" source="_eSovoA0tEey53pgTA4dkHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_f5gYEQ0zEeyr5fjvIKOl-A"/>
        <condition xmi:type="expression:Expression" xmi:id="_f5gYEg0zEeyr5fjvIKOl-A" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_q7kEYA1AEeynMqaWPtKvZg" target="_lB3GEA1AEeynMqaWPtKvZg" source="_MpULUBHJEeyJurGPsxsX6w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_q7krcA1AEeynMqaWPtKvZg"/>
        <condition xmi:type="expression:Expression" xmi:id="_q7krcQ1AEeynMqaWPtKvZg" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_pUAVgBHGEeyJurGPsxsX6w" target="_CW8oMA0qEey53pgTA4dkHg" source="_F-bSkBHHEeyJurGPsxsX6w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_pUAVgRHGEeyJurGPsxsX6w"/>
        <condition xmi:type="expression:Expression" xmi:id="_pUAVghHGEeyJurGPsxsX6w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_wbPzEBHIEeyJurGPsxsX6w" target="_eA24kA0sEey53pgTA4dkHg" source="_uxqmIBHIEeyJurGPsxsX6w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_wbPzERHIEeyJurGPsxsX6w"/>
        <condition xmi:type="expression:Expression" xmi:id="_wbPzEhHIEeyJurGPsxsX6w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_qaSf0BOBEeyttrkuoBOBpQ" target="_oVZDcA0sEey53pgTA4dkHg" source="_fLZZEA0sEey53pgTA4dkHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_qaSf0ROBEeyttrkuoBOBpQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_qaSf0hOBEeyttrkuoBOBpQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_DB8tYBTHEeyu34YKztTfzQ" target="_IL_hsBZ6EeyizpHOufPl4w" source="_7rVsMBTGEeyu34YKztTfzQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_DB8tYRTHEeyu34YKztTfzQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_DB8tYhTHEeyu34YKztTfzQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_jQkUgBTIEeyu34YKztTfzQ" target="_uxqmIBHIEeyJurGPsxsX6w" source="_XnyI8BTHEeyu34YKztTfzQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_jQkUgRTIEeyu34YKztTfzQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_jQkUghTIEeyu34YKztTfzQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cNnVgBTQEey7htL4S3IM2A" target="_eA24kA0sEey53pgTA4dkHg" source="_Ottw8BTHEeyu34YKztTfzQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cNnVgRTQEey7htL4S3IM2A"/>
        <condition xmi:type="expression:Expression" xmi:id="_cNnVghTQEey7htL4S3IM2A" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_S6pcwBZ6EeyizpHOufPl4w" target="_CW8oMA0qEey53pgTA4dkHg" source="_IL_hsBZ6EeyizpHOufPl4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_S6qD0BZ6EeyizpHOufPl4w"/>
        <condition xmi:type="expression:Expression" xmi:id="_S6qD0RZ6EeyizpHOufPl4w" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-63OIBc1EeydQ9O-p9lJOQ" target="_lB3GEA1AEeynMqaWPtKvZg" source="_i_7s8BTHEeyu34YKztTfzQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-65qYBc1EeydQ9O-p9lJOQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_-66RcBc1EeydQ9O-p9lJOQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BFavQBc4EeydQ9O-p9lJOQ" target="_ARMdABc4EeydQ9O-p9lJOQ" source="_lB3GEA1AEeynMqaWPtKvZg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BFavQRc4EeydQ9O-p9lJOQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_BFavQhc4EeydQ9O-p9lJOQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FsF_cBc4EeydQ9O-p9lJOQ" target="_C_vt8Bc4EeydQ9O-p9lJOQ" source="_hRBFYBZ6EeyizpHOufPl4w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FsF_cRc4EeydQ9O-p9lJOQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_FsF_chc4EeydQ9O-p9lJOQ" name="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_rr0qcCJ6EeyedeovCQb2XQ" target="_Ottw8BTHEeyu34YKztTfzQ" source="_v9kOABHHEeyJurGPsxsX6w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_rr0qcSJ6EeyedeovCQb2XQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_rr0qciJ6EeyedeovCQb2XQ" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_-iAMIC_1EeyieZ2hcAfZeA" target="_Qjx2IA0xEeyr5fjvIKOl-A" source="_oVZDcA0sEey53pgTA4dkHg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_-iDPcC_1EeyieZ2hcAfZeA"/>
        <condition xmi:type="expression:Expression" xmi:id="_-iDPcS_1EeyieZ2hcAfZeA" name="" content="" type="TYPE_CONDITION" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_D_yDyw0pEeyMWNmCM-O3tg" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor"/>
      <actors xmi:type="process:Actor" xmi:id="_uBsmUA0pEey53pgTA4dkHg" name="empleado-mesa-entradas"/>
      <actors xmi:type="process:Actor" xmi:id="_5OIpkA0pEey53pgTA4dkHg" name="escribano-area-legales"/>
      <actors xmi:type="process:Actor" xmi:id="_5sRBsBeKEeysAPdnhpesKQ" name="apoderado" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_D_yDzA0pEeyMWNmCM-O3tg"/>
      <documents xmi:type="process:Document" xmi:id="_J1UKUDHhEey03K0u2MSwCw" name="emailFinalizacion" defaultValueIdOfDocumentStore="emailFinalizacion" documentType="INTERNAL">
        <mimeType xmi:type="expression:Expression" xmi:id="_J1UxYDHhEey03K0u2MSwCw" name="html" content="html" returnTypeFixed="true"/>
        <url xmi:type="expression:Expression" xmi:id="_J1UxYTHhEey03K0u2MSwCw" name="" content="" returnTypeFixed="true"/>
        <initialMultipleContent xmi:type="expression:Expression" xmi:id="_J1UxYjHhEey03K0u2MSwCw" name="" content="" type="TYPE_READ_ONLY_SCRIPT" returnType="java.util.List" returnTypeFixed="true"/>
      </documents>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D_yDzQ0pEeyMWNmCM-O3tg">
        <name xmi:type="expression:Expression" xmi:id="_D_yDzg0pEeyMWNmCM-O3tg" name="" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D_yDzw0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D_yD0A0pEeyMWNmCM-O3tg">
        <name xmi:type="expression:Expression" xmi:id="_D_yD0Q0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D_yD0g0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D_yD0w0pEeyMWNmCM-O3tg">
        <name xmi:type="expression:Expression" xmi:id="_D_yD1A0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D_yD1Q0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D_yD1g0pEeyMWNmCM-O3tg">
        <name xmi:type="expression:Expression" xmi:id="_D_yD1w0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D_yD2A0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_D_yD2Q0pEeyMWNmCM-O3tg">
        <name xmi:type="expression:Expression" xmi:id="_D_yD2g0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_D_yD2w0pEeyMWNmCM-O3tg" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_D_yD3A0pEeyMWNmCM-O3tg" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_D_yD3Q0pEeyMWNmCM-O3tg" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_D_yD3g0pEeyMWNmCM-O3tg" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_D_yD3w0pEeyMWNmCM-O3tg" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_D_yD4A0pEeyMWNmCM-O3tg" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_D_yD4Q0pEeyMWNmCM-O3tg" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_D_yD4g0pEeyMWNmCM-O3tg" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_D_yD4w0pEeyMWNmCM-O3tg" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_D_yD5A0pEeyMWNmCM-O3tg" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_D_yD5Q0pEeyMWNmCM-O3tg" type="Process" element="_D_yDsA0pEeyMWNmCM-O3tg" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_D_yD5g0pEeyMWNmCM-O3tg" type="2007" element="_D_yDsQ0pEeyMWNmCM-O3tg">
      <children xmi:type="notation:DecorationNode" xmi:id="_D_yD5w0pEeyMWNmCM-O3tg" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_D_yD6A0pEeyMWNmCM-O3tg" type="7001">
        <children xmi:type="notation:Node" xmi:id="_D_yD6Q0pEeyMWNmCM-O3tg" type="3007" element="_D_yDsg0pEeyMWNmCM-O3tg">
          <children xmi:type="notation:DecorationNode" xmi:id="_D_yD6g0pEeyMWNmCM-O3tg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_D_yD6w0pEeyMWNmCM-O3tg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_udCzow0rEey53pgTA4dkHg" type="3008" element="_udCMkA0rEey53pgTA4dkHg" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_udCzpQ0rEey53pgTA4dkHg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_udCzpg0rEey53pgTA4dkHg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_udCzpA0rEey53pgTA4dkHg" x="230" y="216" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_CW8oPQ0qEey53pgTA4dkHg" type="3005" element="_CW8oMA0qEey53pgTA4dkHg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_CW8oPw0qEey53pgTA4dkHg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_CW8oPg0qEey53pgTA4dkHg" x="192" y="34" width="142" height="71"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_v9k1GBHHEeyJurGPsxsX6w" type="3027" element="_v9kOABHHEeyJurGPsxsX6w" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_v9lcIBHHEeyJurGPsxsX6w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_v9k1GRHHEeyJurGPsxsX6w" x="192" y="387" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_7rWTSBTGEeyu34YKztTfzQ" type="3027" element="_7rVsMBTGEeyu34YKztTfzQ" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_7rWTShTGEeyu34YKztTfzQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_7rWTSRTGEeyu34YKztTfzQ" x="525" y="183" width="178" height="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_OtuYABTHEeyu34YKztTfzQ" type="3027" element="_Ottw8BTHEeyu34YKztTfzQ" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_OtuYAhTHEeyu34YKztTfzQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_OtuYARTHEeyu34YKztTfzQ" x="527" y="382" width="174" height="87"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_QjydMw0xEeyr5fjvIKOl-A" type="3009" element="_Qjx2IA0xEeyr5fjvIKOl-A" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_QjzEQA0xEeyr5fjvIKOl-A" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_QjzEQQ0xEeyr5fjvIKOl-A" x="-91" y="-21"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_QjydNA0xEeyr5fjvIKOl-A" x="1618" y="271" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eSpWvA0tEey53pgTA4dkHg" type="3005" element="_eSovoA0tEey53pgTA4dkHg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eSpWvg0tEey53pgTA4dkHg" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eSpWvQ0tEey53pgTA4dkHg" x="1860" y="146" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_i_7s-RTHEeyu34YKztTfzQ" type="3027" element="_i_7s8BTHEeyu34YKztTfzQ" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_i_7s-xTHEeyu34YKztTfzQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_i_7s-hTHEeyu34YKztTfzQ" x="2149" y="141" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_MpVZcBHJEeyJurGPsxsX6w" type="3027" element="_MpULUBHJEeyJurGPsxsX6w" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_MpVZchHJEeyJurGPsxsX6w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_MpVZcRHJEeyJurGPsxsX6w" x="1860" y="258" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_lB9MsA1AEeynMqaWPtKvZg" type="3009" element="_lB3GEA1AEeynMqaWPtKvZg" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_lB9zwA1AEeynMqaWPtKvZg" type="5020">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_lB9zwQ1AEeynMqaWPtKvZg" x="1" y="29"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_lB9MsQ1AEeynMqaWPtKvZg" x="2339" y="306"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ARMdBBc4EeydQ9O-p9lJOQ" type="3062" element="_ARMdABc4EeydQ9O-p9lJOQ" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_ARNEEBc4EeydQ9O-p9lJOQ" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_ARNEERc4EeydQ9O-p9lJOQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ARMdBRc4EeydQ9O-p9lJOQ" x="2501" y="249"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_D_yD8w0pEeyMWNmCM-O3tg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_D_yD9A0pEeyMWNmCM-O3tg" fontName="Noto Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_D_yD9Q0pEeyMWNmCM-O3tg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_D_yD9g0pEeyMWNmCM-O3tg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D_yD9w0pEeyMWNmCM-O3tg" x="25" y="164" width="2175" height="529"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_05jO8A0pEey53pgTA4dkHg" type="3007" element="_05eWcA0pEey53pgTA4dkHg">
          <children xmi:type="notation:DecorationNode" xmi:id="_05j2AA0pEey53pgTA4dkHg" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_05j2AQ0pEey53pgTA4dkHg" type="7002">
            <children xmi:type="notation:Shape" xmi:id="__jGLEw0qEey53pgTA4dkHg" type="3008" element="__jFkAA0qEey53pgTA4dkHg" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="__jGLFQ0qEey53pgTA4dkHg" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__jGyIA0qEey53pgTA4dkHg" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__jGLFA0qEey53pgTA4dkHg" x="952" y="89"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eA3frA0sEey53pgTA4dkHg" type="3005" element="_eA24kA0sEey53pgTA4dkHg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eA3frg0sEey53pgTA4dkHg" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_fLanMA0sEey53pgTA4dkHg" type="3043" element="_fLZZEA0sEey53pgTA4dkHg" fontName="Noto Sans">
                <children xmi:type="notation:DecorationNode" xmi:id="_fLanMg0sEey53pgTA4dkHg" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_fLanMw0sEey53pgTA4dkHg" x="-95" y="-12"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_fLanMQ0sEey53pgTA4dkHg" x="8" y="52"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eA3frQ0sEey53pgTA4dkHg" x="738" y="81" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oVaRkA0sEey53pgTA4dkHg" type="3027" element="_oVZDcA0sEey53pgTA4dkHg" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_oVaRkg0sEey53pgTA4dkHg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oVaRkQ0sEey53pgTA4dkHg" x="914" y="367" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Node" xmi:id="_xP6HYA0sEey53pgTA4dkHg" type="3015" element="_xP4SMA0sEey53pgTA4dkHg">
              <children xmi:type="notation:DecorationNode" xmi:id="_xP6HZQ0sEey53pgTA4dkHg" type="5010"/>
              <styles xmi:type="notation:DescriptionStyle" xmi:id="_xP6HYQ0sEey53pgTA4dkHg"/>
              <styles xmi:type="notation:FontStyle" xmi:id="_xP6HYg0sEey53pgTA4dkHg" fontName="Noto Sans"/>
              <styles xmi:type="notation:LineStyle" xmi:id="_xP6HYw0sEey53pgTA4dkHg"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xP6HZA0sEey53pgTA4dkHg" x="439" y="387" width="377" height="191"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_XnywCBTHEeyu34YKztTfzQ" type="3027" element="_XnyI8BTHEeyu34YKztTfzQ" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_XnywChTHEeyu34YKztTfzQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_XnywCRTHEeyu34YKztTfzQ" x="1259" y="69" width="165" height="83"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_05jO8Q0pEey53pgTA4dkHg"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_05jO8g0pEey53pgTA4dkHg" fontName="Noto Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_05jO8w0pEey53pgTA4dkHg"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_05j2Ag0pEey53pgTA4dkHg"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_05jO9A0pEey53pgTA4dkHg" x="25" y="609" width="2175" height="790"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_xf51YBHFEeyJurGPsxsX6w" type="3007" element="_xfdJcBHFEeyJurGPsxsX6w">
          <children xmi:type="notation:DecorationNode" xmi:id="_xf6cdBHFEeyJurGPsxsX6w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_xf6cdRHFEeyJurGPsxsX6w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_bxuO4w0pEeyMWNmCM-O3tg" type="3002" element="_bxtn0A0pEeyMWNmCM-O3tg" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_bxuO5Q0pEeyMWNmCM-O3tg" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_bxuO5g0pEeyMWNmCM-O3tg" y="26"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_bxuO5A0pEeyMWNmCM-O3tg" x="40" y="55" width="30" height="30"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F-cgvBHHEeyJurGPsxsX6w" type="3005" element="_F-bSkBHHEeyJurGPsxsX6w" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_F-cgvhHHEeyJurGPsxsX6w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F-cgvRHHEeyJurGPsxsX6w" x="144" y="35" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_uxrNMBHIEeyJurGPsxsX6w" type="3005" element="_uxqmIBHIEeyJurGPsxsX6w" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_uxrNMhHIEeyJurGPsxsX6w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uxrNMRHIEeyJurGPsxsX6w" x="1312" y="35" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_IMAIzBZ6EeyizpHOufPl4w" type="3005" element="_IL_hsBZ6EeyizpHOufPl4w" fontName="Noto Sans" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_IMAv0BZ6EeyizpHOufPl4w" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_hRCTgBZ6EeyizpHOufPl4w" type="3043" element="_hRBFYBZ6EeyizpHOufPl4w" fontName="Noto Sans">
                <children xmi:type="notation:DecorationNode" xmi:id="_hRCTghZ6EeyizpHOufPl4w" type="5055">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_hRCTgxZ6EeyizpHOufPl4w" x="66" y="19"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_hRCTgRZ6EeyizpHOufPl4w" x="112" y="62"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_IMAIzRZ6EeyizpHOufPl4w" x="673" y="35" width="140" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_C_wVABc4EeydQ9O-p9lJOQ" type="3062" element="_C_vt8Bc4EeydQ9O-p9lJOQ" fontName="Noto Sans">
              <children xmi:type="notation:DecorationNode" xmi:id="_C_wVAhc4EeydQ9O-p9lJOQ" type="5090">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_C_wVAxc4EeydQ9O-p9lJOQ" x="28" y="21"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_C_wVARc4EeydQ9O-p9lJOQ" x="971" y="35"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_xf6ccBHFEeyJurGPsxsX6w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_xf6ccRHFEeyJurGPsxsX6w" fontName="Noto Sans"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_xf6cchHFEeyJurGPsxsX6w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_xf6cdhHFEeyJurGPsxsX6w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_xf6ccxHFEeyJurGPsxsX6w" x="25" y="10" width="2650" height="185"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_D_yD-A0pEeyMWNmCM-O3tg"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_D_yD-Q0pEeyMWNmCM-O3tg" fontName="Noto Sans"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_D_yD-g0pEeyMWNmCM-O3tg"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_D_yD-w0pEeyMWNmCM-O3tg"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_D_yD_A0pEeyMWNmCM-O3tg" width="2732" height="293"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_D_yD_Q0pEeyMWNmCM-O3tg"/>
    <edges xmi:type="notation:Connector" xmi:id="_D_yD_g0pEeyMWNmCM-O3tg" type="4001" element="_D_yDyA0pEeyMWNmCM-O3tg" source="_bxuO4w0pEeyMWNmCM-O3tg" target="_F-cgvBHHEeyJurGPsxsX6w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_D_yD_w0pEeyMWNmCM-O3tg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_D_yEAA0pEeyMWNmCM-O3tg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_D_yEAQ0pEeyMWNmCM-O3tg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_D_yEAg0pEeyMWNmCM-O3tg" points="[14, -1, -89, -19]$[89, -1, -14, -19]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_lTlNABHGEeyJurGPsxsX6w" id="(0.1,0.7666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_LSoJwA0qEey53pgTA4dkHg" type="4001" element="_LSnisA0qEey53pgTA4dkHg" source="_CW8oPQ0qEey53pgTA4dkHg" target="_udCzow0rEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_LSow0A0qEey53pgTA4dkHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_LSow0Q0qEey53pgTA4dkHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_LSoJwQ0qEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_LSoJwg0qEey53pgTA4dkHg" points="[0, -9, -307, 0]$[301, -10, -6, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LSp-8A0qEey53pgTA4dkHg" id="(1.0,0.62)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_LSp-8Q0qEey53pgTA4dkHg" id="(0.18604651162790697,0.4418604651162791)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_UwvqAA0qEey53pgTA4dkHg" type="4001" element="_Uwub4A0qEey53pgTA4dkHg" source="_udCzow0rEey53pgTA4dkHg" target="_v9k1GBHHEeyJurGPsxsX6w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_UwvqAw0qEey53pgTA4dkHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_UwvqBA0qEey53pgTA4dkHg" x="17" y="8"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_UwvqAQ0qEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_UwvqAg0qEey53pgTA4dkHg" points="[-24, 8, -3, -161]$[-24, 139, -3, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_UwwREA0qEey53pgTA4dkHg" id="(1.0,0.7441860465116279)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Za9WYA0qEey53pgTA4dkHg" type="4001" element="_Za0zgA0qEey53pgTA4dkHg" source="_udCzow0rEey53pgTA4dkHg" target="_7rWTSBTGEeyu34YKztTfzQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Za9WYw0qEey53pgTA4dkHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Za9WZA0qEey53pgTA4dkHg" x="38" y="-23"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Za9WYQ0qEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Za9WYg0qEey53pgTA4dkHg" points="[0, -13, -341, 0]$[261, -13, -80, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Za99cA0qEey53pgTA4dkHg" id="(1.0,0.7906976744186046)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_AsVEAw0rEey53pgTA4dkHg" type="4001" element="_AsVEAA0rEey53pgTA4dkHg" source="_eA3frA0sEey53pgTA4dkHg" target="__jGLEw0qEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_AsVEBg0rEey53pgTA4dkHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_AsVEBw0rEey53pgTA4dkHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_AsVEBA0rEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_AsVEBQ0rEey53pgTA4dkHg" points="[0, -4, -81, 0]$[79, -5, -2, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AsWSIA0rEey53pgTA4dkHg" id="(1.0,0.55)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_AsWSIQ0rEey53pgTA4dkHg" id="(0.046511627906976744,0.4883720930232558)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Krh4EA0rEey53pgTA4dkHg" type="4001" element="_KrhRAA0rEey53pgTA4dkHg" source="__jGLEw0qEey53pgTA4dkHg" target="_XnywCBTHEeyu34YKztTfzQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Krh4Ew0rEey53pgTA4dkHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Krh4FA0rEey53pgTA4dkHg" x="-15" y="-34"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Krh4EQ0rEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Krh4Eg0rEey53pgTA4dkHg" points="[2, 1, -412, -34]$[268, 1, -146, -34]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_KrifIA0rEey53pgTA4dkHg" id="(0.9069767441860465,0.4418604651162791)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_Vi0AgBTHEeyu34YKztTfzQ" id="(0.89,0.9)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rGFpcA0sEey53pgTA4dkHg" type="4001" element="_rGDNMA0sEey53pgTA4dkHg" source="__jGLEw0qEey53pgTA4dkHg" target="_oVaRkA0sEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rGGQgA0sEey53pgTA4dkHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rGGQgQ0sEey53pgTA4dkHg" x="-44" y="-70"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rGFpcQ0sEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rGFpcg0sEey53pgTA4dkHg" points="[-8, -5, -250, -142]$[241, 130, -1, -7]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rGG3kA0sEey53pgTA4dkHg" id="(1.0,0.7674418604651163)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rGG3kQ0sEey53pgTA4dkHg" id="(0.475,0.11666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_GxxtYA0tEey53pgTA4dkHg" type="4003" element="_GxxGUA0tEey53pgTA4dkHg" source="_xP6HYA0sEey53pgTA4dkHg" target="_oVaRkA0sEey53pgTA4dkHg">
      <styles xmi:type="notation:FontStyle" xmi:id="_GxxtYQ0tEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_GxxtYg0tEey53pgTA4dkHg" points="[0, 0, -56, -33]$[52, 33, -4, 0]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GxyUcA0tEey53pgTA4dkHg" id="(1.0,0.11688311688311688)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_GxyUcQ0tEey53pgTA4dkHg" id="(0.03333333333333333,0.55)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q8gaMg0tEey53pgTA4dkHg" type="4001" element="_q8fzIA0tEey53pgTA4dkHg" source="_QjydMw0xEeyr5fjvIKOl-A" target="_eSpWvA0tEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q8gaNQ0tEey53pgTA4dkHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q8gaNg0tEey53pgTA4dkHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q8gaMw0tEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q8gaNA0tEey53pgTA4dkHg" points="[-20, -30, -230, 70]$[-20, -97, -230, 3]$[204, -97, -6, 3]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_q8hBQA0tEey53pgTA4dkHg" id="(1.0,0.7209302325581395)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_q8hBQQ0tEey53pgTA4dkHg" id="(0.05,0.43333333333333335)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wqlXUw0tEey53pgTA4dkHg" type="4001" element="_wqlXUA0tEey53pgTA4dkHg" source="_QjydMw0xEeyr5fjvIKOl-A" target="_MpVZcBHJEeyJurGPsxsX6w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wql-YA0tEey53pgTA4dkHg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wql-YQ0tEey53pgTA4dkHg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wqlXVA0tEey53pgTA4dkHg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wqlXVQ0tEey53pgTA4dkHg" points="[0, -11, -200, -39]$[199, -11, -1, -39]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wqmlcA0tEey53pgTA4dkHg" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wqmlcQ0tEey53pgTA4dkHg" id="(0.008333333333333333,0.7)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_f5g_IA0zEeyr5fjvIKOl-A" type="4001" element="_f5gYEA0zEeyr5fjvIKOl-A" source="_eSpWvA0tEey53pgTA4dkHg" target="_i_7s-RTHEeyu34YKztTfzQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_f5g_Iw0zEeyr5fjvIKOl-A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_f5g_JA0zEeyr5fjvIKOl-A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_f5g_IQ0zEeyr5fjvIKOl-A" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_f5g_Ig0zEeyr5fjvIKOl-A" points="[4, 0, -197, -12]$[173, 0, -28, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_f5iNQA0zEeyr5fjvIKOl-A" id="(0.9666666666666667,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_f5iNQQ0zEeyr5fjvIKOl-A" id="(0.2,0.6571428571428571)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_q7lSgA1AEeynMqaWPtKvZg" type="4001" element="_q7kEYA1AEeynMqaWPtKvZg" source="_MpVZcBHJEeyJurGPsxsX6w" target="_lB9MsA1AEeynMqaWPtKvZg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_q7l5kA1AEeynMqaWPtKvZg" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_q7l5kQ1AEeynMqaWPtKvZg" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_q7lSgQ1AEeynMqaWPtKvZg" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_q7lSgg1AEeynMqaWPtKvZg" points="[25, 57, -438, -28]$[25, 66, -438, -19]$[444, 66, -19, -19]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_q7nHsA1AEeynMqaWPtKvZg" id="(0.2916666666666667,0.05)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_q7nHsQ1AEeynMqaWPtKvZg" id="(0.4418604651162791,0.9302325581395349)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_pUBjoBHGEeyJurGPsxsX6w" type="4001" element="_pUAVgBHGEeyJurGPsxsX6w" source="_F-cgvBHHEeyJurGPsxsX6w" target="_CW8oPQ0qEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_pUBjoxHGEeyJurGPsxsX6w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_pUBjpBHGEeyJurGPsxsX6w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_pUBjoRHGEeyJurGPsxsX6w" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_pUBjohHGEeyJurGPsxsX6w" points="[35, 5, -14, -128]$[35, 98, -14, -35]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_pUDY0BHGEeyJurGPsxsX6w" id="(0.5,0.9333333333333333)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_wbPzExHIEeyJurGPsxsX6w" type="4001" element="_wbPzEBHIEeyJurGPsxsX6w" source="_uxrNMBHIEeyJurGPsxsX6w" target="_eA3frA0sEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_wbQaIBHIEeyJurGPsxsX6w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_wbQaIRHIEeyJurGPsxsX6w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_wbPzFBHIEeyJurGPsxsX6w" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_wbPzFRHIEeyJurGPsxsX6w" points="[-140, 5, 497, -705]$[-269, 5, 368, -705]$[-269, 570, 368, -140]$[-643, 570, -6, -140]$[-643, 709, -6, -1]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_wbRBMBHIEeyJurGPsxsX6w" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_YRnW0BTMEey7htL4S3IM2A" id="(0.6416666666666667,0.016666666666666666)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_qaTG4BOBEeyttrkuoBOBpQ" type="4001" element="_qaSf0BOBEeyttrkuoBOBpQ" source="_fLanMA0sEey53pgTA4dkHg" target="_oVaRkA0sEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_qaTG4xOBEeyttrkuoBOBpQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_qaTG5BOBEeyttrkuoBOBpQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_qaTG4ROBEeyttrkuoBOBpQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_qaTG4hOBEeyttrkuoBOBpQ" points="[-17, 0, -190, -221]$[-17, 127, -190, -94]$[165, 127, -8, -94]$[165, 209, -8, -12]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qaUVABOBEeyttrkuoBOBpQ" id="(1.0,1.0)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_qaUVAROBEeyttrkuoBOBpQ" id="(0.25,0.2)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_DB8tYxTHEeyu34YKztTfzQ" type="4001" element="_DB8tYBTHEeyu34YKztTfzQ" source="_7rWTSBTGEeyu34YKztTfzQ" target="_IMAIzBZ6EeyizpHOufPl4w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_DB8tZhTHEeyu34YKztTfzQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_DB9UcBTHEeyu34YKztTfzQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_DB8tZBTHEeyu34YKztTfzQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_DB8tZRTHEeyu34YKztTfzQ" points="[0, 5, 81, 328]$[12, 5, 93, 328]$[12, -286, 93, 37]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DB97gBTHEeyu34YKztTfzQ" id="(1.0,0.42857142857142855)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_DB97gRTHEeyu34YKztTfzQ" id="(0.014285714285714285,0.4714285714285714)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_jQkUgxTIEeyu34YKztTfzQ" type="4001" element="_jQkUgBTIEeyu34YKztTfzQ" source="_XnywCBTHEeyu34YKztTfzQ" target="_uxrNMBHIEeyJurGPsxsX6w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_jQkUhhTIEeyu34YKztTfzQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_jQkUhxTIEeyu34YKztTfzQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_jQkUhBTIEeyu34YKztTfzQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_jQkUhRTIEeyu34YKztTfzQ" points="[-2, -41, -43, 657]$[-2, -686, -43, 12]"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_jQlioRTIEeyu34YKztTfzQ" id="(0.5,0.8285714285714286)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cNqY0BTQEey7htL4S3IM2A" type="4001" element="_cNnVgBTQEey7htL4S3IM2A" source="_OtuYABTHEeyu34YKztTfzQ" target="_eA3frA0sEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cNq_4BTQEey7htL4S3IM2A" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cNq_4RTQEey7htL4S3IM2A" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cNqY0RTQEey7htL4S3IM2A" fontName="Fira Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cNqY0hTQEey7htL4S3IM2A" points="[-66, 37, 0, -306]$[-66, 339, 0, -4]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cNs1EBTQEey7htL4S3IM2A" id="(1.0,0.4714285714285714)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_cNs1ERTQEey7htL4S3IM2A" id="(0.30833333333333335,0.06666666666666667)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_S6qq4BZ6EeyizpHOufPl4w" type="4001" element="_S6pcwBZ6EeyizpHOufPl4w" source="_IMAIzBZ6EeyizpHOufPl4w" target="_CW8oPQ0qEey53pgTA4dkHg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_S6rR8BZ6EeyizpHOufPl4w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_S6rR8RZ6EeyizpHOufPl4w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_S6qq4RZ6EeyizpHOufPl4w" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_S6qq4hZ6EeyizpHOufPl4w" points="[-140, 1, 376, -152]$[-469, 1, 47, -152]$[-469, 186, 47, 33]$[-479, 186, 37, 33]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S6tuMBZ6EeyizpHOufPl4w" id="(1.0,0.4714285714285714)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_S6tuMRZ6EeyizpHOufPl4w" id="(0.7394366197183099,0.028169014084507043)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-67fkBc1EeydQ9O-p9lJOQ" type="4001" element="_-63OIBc1EeydQ9O-p9lJOQ" source="_i_7s-RTHEeyu34YKztTfzQ" target="_lB9MsA1AEeynMqaWPtKvZg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-68GoBc1EeydQ9O-p9lJOQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-68GoRc1EeydQ9O-p9lJOQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-67fkRc1EeydQ9O-p9lJOQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-67fkhc1EeydQ9O-p9lJOQ" points="[0, 1, -70, -133]$[71, 1, 1, -133]$[71, 132, 1, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-6970Bc1EeydQ9O-p9lJOQ" id="(1.0,0.4714285714285714)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-6970Rc1EeydQ9O-p9lJOQ" id="(0.46511627906976744,0.046511627906976744)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BFbWUBc4EeydQ9O-p9lJOQ" type="4001" element="_BFavQBc4EeydQ9O-p9lJOQ" source="_lB9MsA1AEeynMqaWPtKvZg" target="_ARMdBBc4EeydQ9O-p9lJOQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BFbWUxc4EeydQ9O-p9lJOQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BFbWVBc4EeydQ9O-p9lJOQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BFbWURc4EeydQ9O-p9lJOQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BFbWUhc4EeydQ9O-p9lJOQ" points="[-7, -18, -132, 59]$[119, -79, -6, -2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BFckcBc4EeydQ9O-p9lJOQ" id="(1.0,0.7441860465116279)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_BFckcRc4EeydQ9O-p9lJOQ" id="(0.2,0.4)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FsH0oBc4EeydQ9O-p9lJOQ" type="4001" element="_FsF_cBc4EeydQ9O-p9lJOQ" source="_hRCTgBZ6EeyizpHOufPl4w" target="_C_wVABc4EeydQ9O-p9lJOQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FsH0oxc4EeydQ9O-p9lJOQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FsH0pBc4EeydQ9O-p9lJOQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FsH0oRc4EeydQ9O-p9lJOQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FsH0ohc4EeydQ9O-p9lJOQ" points="[2, 1, -185, 72]$[61, 1, -126, 72]$[61, -61, -126, 10]$[186, -61, -1, 10]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FsIbsBc4EeydQ9O-p9lJOQ" id="(0.92,0.96)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_FsIbsRc4EeydQ9O-p9lJOQ" id="(0.16666666666666666,0.5)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_rr1RgCJ6EeyedeovCQb2XQ" type="4001" element="_rr0qcCJ6EeyedeovCQb2XQ" source="_v9k1GBHHEeyJurGPsxsX6w" target="_OtuYABTHEeyu34YKztTfzQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_rr1RgyJ6EeyedeovCQb2XQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_rr1RhCJ6EeyedeovCQb2XQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_rr1RgSJ6EeyedeovCQb2XQ" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_rr1RgiJ6EeyedeovCQb2XQ" points="[0, -3, -318, -44]$[215, -3, -103, -44]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rr14kCJ6EeyedeovCQb2XQ" id="(1.0,0.5333333333333333)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_rr14kSJ6EeyedeovCQb2XQ" id="(0.5919540229885057,0.896551724137931)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_-iFEoC_1EeyieZ2hcAfZeA" type="4001" element="_-iAMIC_1EeyieZ2hcAfZeA" source="_oVaRkA0sEey53pgTA4dkHg" target="_QjydMw0xEeyr5fjvIKOl-A" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_-iFrsC_1EeyieZ2hcAfZeA" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_-iFrsS_1EeyieZ2hcAfZeA" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_-iFEoS_1EeyieZ2hcAfZeA" fontName="Noto Sans"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_-iFEoi_1EeyieZ2hcAfZeA" points="[0, 0, -606, 615]$[606, -613, 0, 2]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-iHg4C_1EeyieZ2hcAfZeA" id="(1.0,0.48333333333333334)"/>
      <targetAnchor xmi:type="notation:IdentityAnchor" xmi:id="_-iHg4S_1EeyieZ2hcAfZeA" id="(0.5116279069767442,0.9069767441860465)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
